name: Hello World

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  run-custom-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run custom script
      run: |
        chmod +x ./run.sh
        ./run.sh
      
    - name: Verify script execution
      run: |
        if [ -f ./run.sh ]; then
          echo "Script executed successfully!"
        else
          echo "Script not found"
          exit 1
        fi
